# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pillarGUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.graphView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphView.setGeometry(QtCore.QRect(270, 20, 501, 331))
        self.graphView.setObjectName("graphView")
        self.openButton = QtWidgets.QPushButton(self.centralwidget)
        self.openButton.setGeometry(QtCore.QRect(50, 260, 161, 28))
        self.openButton.setObjectName("openButton")
        self.closeButton = QtWidgets.QPushButton(self.centralwidget)
        self.closeButton.setGeometry(QtCore.QRect(50, 310, 161, 28))
        self.closeButton.setObjectName("closeButton")
        self.stopButton = QtWidgets.QPushButton(self.centralwidget)
        self.stopButton.setGeometry(QtCore.QRect(50, 360, 161, 28))
        self.stopButton.setAutoFillBackground(False)
        self.stopButton.setObjectName("stopButton")
        self.zeroButton = QtWidgets.QPushButton(self.centralwidget)
        self.zeroButton.setGeometry(QtCore.QRect(50, 510, 161, 28))
        self.zeroButton.setObjectName("zeroButton")
        self.breakButton = QtWidgets.QPushButton(self.centralwidget)
        self.breakButton.setGeometry(QtCore.QRect(50, 460, 161, 28))
        self.breakButton.setObjectName("breakButton")
        self.homeButton = QtWidgets.QPushButton(self.centralwidget)
        self.homeButton.setGeometry(QtCore.QRect(50, 410, 161, 28))
        self.homeButton.setObjectName("homeButton")
        self.CSVGenerateButton = QtWidgets.QPushButton(self.centralwidget)
        self.CSVGenerateButton.setGeometry(QtCore.QRect(50, 110, 161, 28))
        self.CSVGenerateButton.setObjectName("CSVGenerateButton")
        self.distanceButton = QtWidgets.QPushButton(self.centralwidget)
        self.distanceButton.setGeometry(QtCore.QRect(50, 190, 161, 28))
        self.distanceButton.setObjectName("distanceButton")
        self.csvName = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.csvName.setGeometry(QtCore.QRect(50, 70, 161, 31))
        self.csvName.setObjectName("csvName")
        self.distanceInput = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.distanceInput.setGeometry(QtCore.QRect(50, 150, 161, 31))
        self.distanceInput.setObjectName("distanceInput")
        self.liveDataFeed = QtWidgets.QTextBrowser(self.centralwidget)
        self.liveDataFeed.setGeometry(QtCore.QRect(270, 370, 501, 131))
        self.liveDataFeed.setObjectName("liveDataFeed")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.openButton.setText(_translate("MainWindow", "Open"))
        self.closeButton.setText(_translate("MainWindow", "Close"))
        self.stopButton.setText(_translate("MainWindow", "Stop"))
        self.zeroButton.setText(_translate("MainWindow", "Zero Position"))
        self.breakButton.setText(_translate("MainWindow", "Break"))
        self.homeButton.setText(_translate("MainWindow", "Home"))
        self.CSVGenerateButton.setText(_translate("MainWindow", "Generate CSV"))
        self.distanceButton.setText(_translate("MainWindow", "Move to Distance"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
